<?xml version="1.0"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 
	xmlns:tns="http://privados.recintos.ws" targetNamespace="http://privados.recintos.ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://privados.recintos.ws" schemaLocation="objetosSimples.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:service name="OperacionEntradaService">
        <wsdl:port name="OperacionEntradaPort" binding="tns:OperacionEntradaPortBinding">
            <soap:address/>
        </wsdl:port>
    </wsdl:service>
    <wsdl:message name="recibeTraspaleo">
        <wsdl:part name="parameters" element="tns:recibeTraspaleo"/>
    </wsdl:message>
    <wsdl:binding name="OperacionEntradaPortBinding" type="tns:OperacionEntrada">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    </wsdl:binding>
    <wsdl:portType name="OperacionEntrada">
        <wsdl:operation name="recibeTraspaleo">
            <wsdl:input message="tns:recibeTraspaleo"/>
        </wsdl:operation>
    </wsdl:portType>

</wsdl:definitions>