<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getConfigValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">CS8vIGdldCBwaXBlbGluZSBpbnB1dAoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsKCVN0cmluZwljb25maWdLZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImNvbmZpZ0tleSIgKTsKCVN0cmluZwlkZWZhdWx0Q29uZmlnVmFs
dWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRlZmF1bHRDb25maWdW
YWx1ZSIgKTsKCQoJLy8gbG9va3VwIHVzaW5nIHRoZSBwcmUtbG9hZGVkIGNvbmZpZ1Byb3AKCVN0
cmluZyB2YWx1ZSA9IGNvbmZpZ1Byb3AuZ2V0UHJvcGVydHkoY29uZmlnS2V5LCBkZWZhdWx0Q29u
ZmlnVmFsdWUpOwoKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAiY29uZmlnVmFsdWUi
LCB2YWx1ZSk7CglwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7CgoK</value>
</Values>
